POST http://localhost:3030/events
Content-Type: application/json

{
    "title": "Event Seniors Dev",
    "details": "Event for devlopers seniors",
    "maxAttendees": 10
}

###
POST http://localhost:3030/events/6a9f8963-4a64-41bd-9fd7-e04fcacf98bc/attendee
Content-Type: application/json

{
    "name": "Niet",
    "email": "niet@dev.net"
}

###
GET http://localhost:3030/events/6a9f8963-4a64-41bd-9fd7-e04fcacf98bc

###
GET http://localhost:3030/attendee/4/badge

###
GET http://localhost:3030/attendees/3/check-in

###
GET http://localhost:3030/events/6a9f8963-4a64-41bd-9fd7-e04fcacf98bc/attendees

