POST http://localhost:3030/events
Content-Type: application/json

{
    "title": "Nlw Unite",
    "details": "Event for devlopers",
    "maxAttendees": 200
}

###
POST http://localhost:3030/events/36c82a78-32f6-4367-b84f-bef24db224f7/attendee
Content-Type: application/json

{
    "name": "Miau Cruz",
    "email": "miau@dev.net"
}

###
GET http://localhost:3030/events/36c82a78-32f6-4367-b84f-bef24db224f7

###
GET http://localhost:3030/attendee/10/badge

###
GET http://localhost:3030/attendees/10/check-in

###
GET http://localhost:3030/events/36c82a78-32f6-4367-b84f-bef24db224f7/attendees

